dist: xenial
language: python
cache: pip

matrix:
  include:
    - python: "3.7"
      env: PYTHONVER=3

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - graphviz
  homebrew:
    update: true
    packages:
      - python
      - graphviz
      - python2

install:
    - python3 -m pip install -r requirements.txt && python3 -m pip install -e .[dev]
    - python3 -m pip install -U --target=`pwd` --no-deps pyEX  # install latest pyEX base
    - git checkout pyEX/zipline  # the above install clobbers source, so restore

script: make test

after_success:
    - codecov --token 54b6b05c-ae12-4cb5-936c-5ca7a7d5fe3f

branches:
  only:
  - master

notifications:
  email: false
